apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
spec:
  project: default
  source:
    repoURL: <REPO_URL> # Replace with the URL of your Git repository
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-staging.yaml
      releaseName: techtrends-staging
      chart: techtrends
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true