apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
spec:
  project: default
  source:
    repoURL: https://github.com/kydq2022/cloud-native-application-architecture-p1.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-prod.yaml
      releaseName: techtrends-prod
      chart: techtrends
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true